### 1. Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [85]:
def vandermonde(avector,n,increasing=True):
    """
    This function populate a vandermonde matrix based on the input vector 
    and the number of columns in the output matrix specified.
    
    Arguments
    ---------
    avector = numpy.array , array of numbers int/float
    n       = int , number of columns required in the output matrix
    """
    print("""Given vector:""",avector)
    print("Total number of columns in the output matrix:",n)
    print("Increasing Vandemonde matrix:",increasing)
    
    if increasing:
        vandemonde_matrix = np.array([x**i for x in avector for i in range(n)]).reshape(avector.size,n)
        print (vandemonde_matrix)
    if not increasing:
        vandemonde_matrix = np.array([x**(n-i-1) for x in avector for i in range(n)]).reshape(avector.size,n)
        print (vandemonde_matrix)
    

In [86]:
a = np.array([1,2,3,4,5])

In [90]:
vandermonde(a,5,increasing=True)

Given vector: [1 2 3 4 5]
Total number of columns in the output matrix: 5
Increasing Vande monde matrix: True
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [91]:
vandermonde(a,5,increasing=False)       

Given vector: [1 2 3 4 5]
Total number of columns in the output matrix: 5
Increasing Vande monde matrix: False
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [93]:
b=np.array([1,2,4,6,8,10])
vandermonde(b,3,increasing=False)   

Given vector: [ 1  2  4  6  8 10]
Total number of columns in the output matrix: 3
Increasing Vande monde matrix: False
[[  1   1   1]
 [  4   2   1]
 [ 16   4   1]
 [ 36   6   1]
 [ 64   8   1]
 [100  10   1]]


### 2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below
### i 1 2 3 4 5 6 7 8 9 10
### ===== == == == == == == == == == ==
### Input 10 20 30 40 50 60 70 80 90 100
### y1 25 = (10+20+30+40)/4
### y2 35 = (20+30+40+50)/4
### y3 45 = (30+40+50+60)/4
### y4 55 = (40+50+60+70)/4
### y5 65 = (50+60+70+80)/4
### y6 75 = (60+70+80+90)/4
### y7 85 = (70+80+90+100)/4
### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

### Question: Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [152]:
def moving_average(anarray,window):
    """
    This function will return an array of moving average values
    
    anarray - numpy.array
    window - int
    """
    
    if window == 0:
        return None
    size = anarray.size
    no_moving_average_values = size - window +1
    print("Length of the input array:",size)    
    print("Number of moving average values for an array with size",size,"over a window of",window,"is",no_moving_average_values)
    moving_avgs = np.empty((no_moving_average_values))
    for i in range(no_moving_average_values):
        moving_avgs[i] = anarray[i:i+window].mean()
    return moving_avgs

In [154]:
test = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
output = moving_average(test,3)
output

Length of the input array: 13
Number of moving average values for an array with size 13 over a window of 3 is 11


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])